services:
  warotickets:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${HOST_PORT:-3003}:3003"
    volumes:
      - nuxt-data:/app/storage
    networks:
      - warolabs-network

networks:
  warolabs-network:
    external: true

volumes:
  nuxt-data:
